### ISSUE TITLE
container-build doesn't work on macos

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#3]
Possibly something specific to my macbook, but I see this:

```
Building: cerc/ipld-eth-server
Script: container-build/cerc-ipld-eth-server/build.sh
exec: "com.docker.cli": executable file not found in $PATH
```

Interwebs say this may be something to do with zsh. To be investigated further. Docker in general works on the machine.

**Comment by dboreham** [comment]
Tussled with this some more. The initial problem appears to be specific to my macbook. After reinstalling Docker Desktop, that problem was cured.

However, there's now a second, similar problem:

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
```

I've reproduced this on a mac mini at AWS, so it's not specific to my machine.

**Comment by dboreham** [comment]
Seems to be fixed by this: https://stackoverflow.com/questions/67642620/docker-credential-desktop-not-installed-or-not-available-in-path but very odd that we have the problem in an entirely greenfield docker desktop installation.

**Comment by dboreham** [comment]
Current workaround: rename `~/.docker/config.json` -> `./docker/config.json-saved`

**Comment by rickmanelius** [comment]
Yes yes. I had this snag me yet again, and just deleted `~/.docker/config.json` to get by it.

@zramsay So I tried this again with the [v1.0.5-alpha](https://github.com/cerc-io/stack-orchestrator/releases/tag/v1.0.5-alpha) release and [the updated docs you provided last night](http://docs-staging.laconic.com/docs/tutorials/quick-start/). Now I'm getting stuck at the stack stand-up step because of a Python error.

```
  File "/Users/rickmanelius/.shiv/laconic-so_23bc390eae8bbd8a4216b226b4454edf233fa21431364bc1495796b58a35e576/site-packages/app/deploy_system.py", line 44, in command
    compose_dir = Path(__file__).absolute().parent.joinpath("data", "compose")
NameError: name 'Path' is not defined. Did you mean: 'path'?
```

It looks like we didn't import the `Path` module needed here https://github.com/cerc-io/stack-orchestrator/blob/main/app/deploy_system.py#L44.

Looks like we might need `from pathlib import Path`

**Comment by rickmanelius** [comment]
Duly noted. I'll keep this open a meta ticket and spin off sub-issues until I complete this happy path for macOS 👍

**Comment by rickmanelius** [comment]
@zramsay I'm happy to report I was able to fully step through the [quick-start tutorial](http://docs-staging.laconic.com/docs/tutorials/quick-start/) on macOS. Closing
