### ISSUE TITLE
Next.js consumes run-time config at build time

### ISSUE THREAD

**Issue by dboreham** [cerc-io/stack-orchestrator#633]
This came up trying to package the [iglootools](https://github.com/snowball-tools/iglootools-home/tree/sdk) app. It seems to be a manifestation of this bug: https://github.com/vercel/next.js/issues/45383

The symptoms are that at build time it fails if a (valid) API key for bugsnag is not provided.
This obviously makes no sense because bugsnag is a thing concerned with run time state,
and has no business being invoked at build time.

Add details here on exactly what's happening and how/if we can work around:

This has more background: https://stackoverflow.com/questions/70764556/whats-the-difference-between-exposing-environment-variables-in-nextjs-through-t

And the bug above continues on this discussion forum where they eventually announce a redesigned process for build/config/pre-render: https://github.com/vercel/next.js/discussions/46544#discussioncomment-7115457

**Comment by telackey** [comment]
This seems to be "standard behavior" for next, so that it can pre-render static HTML.  This is obviously a bad system though, as it makes it practically impossible to build a generic container which will be deployed with different configuration at runtime.

That is, with the standard `next build` step, the distinction between build time and runtime has been blurred to such an extent that practically it has to be built at runtime.

Fortunately, there is a partial fix/workaround in the new `next experimental-compile` and `next experimental generate` commands.

With these, the build process gets split in half.  The compilation step can be done generically, while the "generate" step still requires runtime config.

We have incorporated this into our scripts, such that for the compile step environment variables are replaced with placeholders, and are replaced with true values just before running generate.

Unfortunately, the `experimental-generate` step is still quite experimental, and we uncovered a bug that would cause the build to hang.

I opened an issue with next.js here identifying the issue: https://github.com/vercel/next.js/issues/58274

And a PR fixing it here: https://github.com/vercel/next.js/pull/58276

In the meantime I added a workaround in the build script which will scrape the output to discover when the generate step has completed, then signal the process to exit.
